import type { Block } from './email-html-renderer'

export interface TemplatePreset {
  id: string
  name: string
  category: string
  tag: string
  tagColor: string
  desc: string
  rate: string
  accent: string
  heroGrad: string
  pillBg: string
  blocks: Block[]
  defaultSubject: string
  defaultPrompt: string
  imageUrl?: string
  isPremium?: boolean
}

export const templatePresets: TemplatePreset[] = [
  {
    id: 'cart',
    name: 'Sepet Terk',
    category: 'cart',
    tag: 'Popüler',
    tagColor: 'text-amber-400',
    desc: '%15 indirimle geri kazan',
    rate: '%32 dönüşüm',
    accent: '#3b82f6',
    heroGrad: 'from-[#0a1628] via-[#0d1f3c] to-[#0a1628]',
    pillBg: 'bg-blue-500/15 text-blue-400',
    imageUrl: '/templates/cart.png',
    defaultSubject: 'Sepetiniz sizi bekliyor 🛒',
    defaultPrompt: 'Sepeti terk eden müşteriler için %15 özel indirimli premium bir kampanya oluştur.',
    blocks: [
      { id: 'b1', type: 'hero', c: { headline: '⚡ Sepetiniz Sizi Bekliyor', sub: 'Özel %15 indiriminizi kaçırmayın!', badge: 'Sınırlı Süre', bgColor: '#0a1628' } },
      { id: 'b2', type: 'text', c: { body: 'Merhaba {{isim}},\n\nSepetiinizde bıraktığınız ürünleri hâlâ saklıyoruz. Ama bu fırsat uzun sürmeyecek!\n\nSadece sizin için özel bir indirim hazırladık. Aşağıdaki kodu kullanarak sepetinizi tamamlayın.' } },
      { id: 'b3', type: 'coupon', c: { code: 'SEPET15', discount: '%15 Özel İndirim', expiry: 'Son 48 saat!' } },
      { id: 'b4', type: 'cta', c: { label: 'Sepetime Dön →', sub: 'Ücretsiz kargo · Güvenli ödeme', color: '#3b82f6' } },
      { id: 'b5', type: 'divider', c: {} },
      { id: 'b6', type: 'benefits', c: { items: 'Ücretsiz kargo\nKolay iade\nGüvenli SSL ödeme' } },
      { id: 'b7', type: 'footer', c: { brand: 'Mağazanız', addr: 'İstanbul, Türkiye', unsub: 'Abonelikten çık' } },
    ],
  },
  {
    id: 'vip',
    name: 'VIP Koleksiyon',
    category: 'vip',
    tag: 'Premium',
    tagColor: 'text-amber-400',
    desc: 'Sadık müşterilere özel',
    rate: '%41 dönüşüm',
    accent: '#f59e0b',
    heroGrad: 'from-[#1a1000] via-[#2d1c00] to-[#1a1000]',
    pillBg: 'bg-amber-500/15 text-amber-400',
    imageUrl: '/templates/vip.png',
    isPremium: true,
    defaultSubject: 'VIP üyemiz olarak size özel bir teklif var 👑',
    defaultPrompt: 'VIP müşterilere özel erken erişim ve %20 özel indirim kampanyası.',
    blocks: [
      { id: 'b1', type: 'hero', c: { headline: '👑 VIP Koleksiyonunuz Hazır', sub: 'Sadece sizin için erken erişim fırsatı', badge: 'VIP ÜYELERİMİZE ÖZEL', bgColor: '#1a1000' } },
      { id: 'b2', type: 'text', c: { body: 'Sayın {{isim}},\n\nSadık müşterilerimizden biri olarak, yeni koleksiyonumuza herkesten önce erişme ayrıcalığına sahipsiniz.\n\nBu özel teklifimiz yalnızca 72 saat geçerlidir.' } },
      { id: 'b3', type: 'coupon', c: { code: 'VIP20', discount: '%20 Özel İndirim', expiry: 'Yalnızca 72 saat geçerli' } },
      { id: 'b4', type: 'cta', c: { label: 'Koleksiyonu Keşfet →', sub: 'Erken erişim · Öncelikli teslimat', color: '#f59e0b' } },
      { id: 'b5', type: 'divider', c: {} },
      { id: 'b6', type: 'benefits', c: { items: 'Erken erişim avantajı\nÖncelikli kargo\nKişisel müşteri hizmetleri' } },
      { id: 'b7', type: 'footer', c: { brand: 'Mağazanız', addr: 'İstanbul, Türkiye', unsub: 'Abonelikten çık' } },
    ],
  },
  {
    id: 'launch',
    name: 'Ürün Lansmanı',
    category: 'launch',
    tag: 'Yeni',
    tagColor: 'text-violet-400',
    desc: 'Yeni koleksiyon tanıtımı',
    rate: '%28 dönüşüm',
    accent: '#8b5cf6',
    heroGrad: 'from-[#0f0a28] via-[#1a0f3d] to-[#0f0a28]',
    pillBg: 'bg-violet-500/15 text-violet-400',
    imageUrl: '/templates/launch.png',
    isPremium: true,
    defaultSubject: 'Yeni koleksiyon geldi — İlk siz görün ✨',
    defaultPrompt: 'Yeni premium koleksiyon için heyecan verici bir lansman kampanyası.',
    blocks: [
      { id: 'b1', type: 'hero', c: { headline: '✨ Yeni Koleksiyon Geldi', sub: 'Bu sezonu tanımlayan parçalar şimdi burada', badge: 'YENİ KOLEKSİYON', bgColor: '#0f0a28' } },
      { id: 'b2', type: 'text', c: { body: 'Merhaba {{isim}},\n\nBu sezonun en çok beklenen koleksiyonu nihayet burada! Özenle seçilmiş parçalar, premium kalite ve sizi en iyi hissettiren tasarımlar.\n\nStoklar kısıtlı, kaçırmayın.' } },
      { id: 'b3', type: 'cta', c: { label: 'Yeni Koleksiyonu İncele →', sub: 'Stoklar kısıtlı · Ücretsiz kargo', color: '#8b5cf6' } },
      { id: 'b4', type: 'divider', c: {} },
      { id: 'b5', type: 'benefits', c: { items: 'Premium kalite malzeme\nÖzel tasarım\nHızlı teslimat' } },
      { id: 'b6', type: 'footer', c: { brand: 'Mağazanız', addr: 'İstanbul, Türkiye', unsub: 'Abonelikten çık' } },
    ],
  },
  {
    id: 'flash',
    name: 'Flash Sale',
    category: 'promo',
    tag: 'Acil',
    tagColor: 'text-red-400',
    desc: 'Son 24 saat aciliyet',
    rate: '%38 dönüşüm',
    accent: '#ef4444',
    heroGrad: 'from-[#1a0808] via-[#2d0f0f] to-[#1a0808]',
    pillBg: 'bg-red-500/15 text-red-400',
    imageUrl: '/templates/flash.png',
    defaultSubject: '⏰ Son 24 saat — %30 indirim kaçmayın!',
    defaultPrompt: 'Son 24 saat flash sale kampanyası. Maksimum aciliyet.',
    blocks: [
      { id: 'b1', type: 'hero', c: { headline: '🔥 Flash Sale — Son 24 Saat!', sub: 'Bu fırsatı kaçırmayın — gece yarısı sona eriyor', badge: '⏰ SINIRLI SÜRE', bgColor: '#1a0808' } },
      { id: 'b2', type: 'text', c: { body: 'Merhaba {{isim}},\n\nBu fırsatı bekliyordunuz! Seçili tüm ürünlerde %30\'a varan indirim — ama sadece 24 saat!\n\nGece yarısı sona eriyor. Şimdi harekete geçin.' } },
      { id: 'b3', type: 'coupon', c: { code: 'FLASH30', discount: '%30\'a Kadar İndirim', expiry: '⏰ Gece yarısı sona eriyor!' } },
      { id: 'b4', type: 'cta', c: { label: '⚡ Hemen Alışverişe Başla', sub: 'Ücretsiz kargo · Kolay iade', color: '#ef4444' } },
      { id: 'b5', type: 'footer', c: { brand: 'Mağazanız', addr: 'İstanbul, Türkiye', unsub: 'Abonelikten çık' } },
    ],
  },
  {
    id: 'winback',
    name: 'Win-Back',
    category: 'winback',
    tag: 'Etkili',
    tagColor: 'text-emerald-400',
    desc: 'Pasif müşteriyi geri çek',
    rate: '%19 dönüşüm',
    accent: '#10b981',
    heroGrad: 'from-[#051a0d] via-[#0a2d18] to-[#051a0d]',
    pillBg: 'bg-emerald-500/15 text-emerald-400',
    imageUrl: '/templates/winback.png',
    isPremium: true,
    defaultSubject: 'Sizi özledik {{isim}} 💚',
    defaultPrompt: 'Uzun süredir alışveriş yapmayan müşterileri geri kazanmak için kampanya.',
    blocks: [
      { id: 'b1', type: 'hero', c: { headline: '💚 Sizi Özledik!', sub: 'Geri dönmeniz için özel bir sürpriz hazırladık', badge: 'SİZE ÖZEL', bgColor: '#051a0d' } },
      { id: 'b2', type: 'text', c: { body: 'Merhaba {{isim}},\n\nBir süredir sizi göremedik ve özledik. Geri dönmeniz için özel bir hediye hazırladık.\n\nBu kodu kullanarak ilk alışverişinizde indirimden faydalanın!' } },
      { id: 'b3', type: 'coupon', c: { code: 'OZLEDIK15', discount: '%15 Hoş Geldin İndirimi', expiry: '30 gün geçerli' } },
      { id: 'b4', type: 'cta', c: { label: 'Alışverişe Dön →', sub: 'Sizi tekrar görmek ne güzel!', color: '#10b981' } },
      { id: 'b5', type: 'footer', c: { brand: 'Mağazanız', addr: 'İstanbul, Türkiye', unsub: 'Abonelikten çık' } },
    ],
  },
  {
    id: 'birthday',
    name: 'Doğum Günü',
    category: 'birthday',
    tag: 'Kişisel',
    tagColor: 'text-pink-400',
    desc: 'Kişisel sürpriz kampanyası',
    rate: '%44 dönüşüm',
    accent: '#ec4899',
    heroGrad: 'from-[#1a0814] via-[#2d0f20] to-[#1a0814]',
    pillBg: 'bg-pink-500/15 text-pink-400',
    imageUrl: '/templates/birthday.png',
    isPremium: true,
    defaultSubject: '🎂 Doğum günün kutlu olsun {{isim}}!',
    defaultPrompt: 'Müşterinin doğum günü için sıcak ve kişisel bir kampanya.',
    blocks: [
      { id: 'b1', type: 'hero', c: { headline: '🎂 Doğum Günün Kutlu Olsun!', sub: 'Bu özel gün için sana bir sürpriz hazırladık', badge: '🎁 SÜRPRIZ HEDİYE', bgColor: '#1a0814' } },
      { id: 'b2', type: 'text', c: { body: 'Sevgili {{isim}},\n\nDoğum günün kutlu olsun! Bu özel gününüzde yanınızda olmak istedik.\n\nSana özel bir hediye hazırladık. Aşağıdaki kodu kullanarak sürprizini keşfet!' } },
      { id: 'b3', type: 'coupon', c: { code: 'DOGUMGUN20', discount: '%20 Doğum Günü İndirimi 🎁', expiry: '7 gün geçerli' } },
      { id: 'b4', type: 'cta', c: { label: '🎁 Hediyeni Al →', sub: 'Doğum günün kutlu olsun!', color: '#ec4899' } },
      { id: 'b5', type: 'footer', c: { brand: 'Mağazanız', addr: 'İstanbul, Türkiye', unsub: 'Abonelikten çık' } },
    ],
  },
  {
    id: 'welcome',
    name: 'Hoş Geldin',
    category: 'welcome',
    tag: 'Temel',
    tagColor: 'text-teal-400',
    desc: 'İlk izlenimi mükemmel yap',
    rate: '%37 dönüşüm',
    accent: '#059669',
    heroGrad: 'from-[#031a14] via-[#052d20] to-[#031a14]',
    pillBg: 'bg-teal-500/15 text-teal-400',
    imageUrl: '/templates/welcome.png',
    defaultSubject: 'Hoş geldin {{isim}}! Başlamak için hazır mısın? 🌟',
    defaultPrompt: 'Yeni müşteriye hoş geldin kampanyası.',
    blocks: [
      { id: 'b1', type: 'hero', c: { headline: '🌟 Hoş Geldiniz!', sub: 'Ailemize katıldığınız için teşekkürler', badge: 'HOŞ GELDİNİZ', bgColor: '#031a14' } },
      { id: 'b2', type: 'text', c: { body: 'Merhaba {{isim}},\n\nBize katıldığınız için çok mutluyuz! Ailemizin yeni bir üyesi olarak sizi özel hissettirmek istiyoruz.\n\nİlk alışverişinizde size özel bir indirim sunuyoruz.' } },
      { id: 'b3', type: 'coupon', c: { code: 'HOSGELDIN10', discount: '%10 İlk Alışveriş İndirimi', expiry: '30 gün geçerli' } },
      { id: 'b4', type: 'cta', c: { label: 'Alışverişe Başla →', sub: 'Ücretsiz kargo · İlk siparişte', color: '#059669' } },
      { id: 'b5', type: 'divider', c: {} },
      { id: 'b6', type: 'benefits', c: { items: 'İlk siparişte ücretsiz kargo\n7/24 müşteri desteği\nKolay iade garantisi' } },
      { id: 'b7', type: 'footer', c: { brand: 'Mağazanız', addr: 'İstanbul, Türkiye', unsub: 'Abonelikten çık' } },
    ],
  },
  {
    id: 'restock',
    name: 'Stoğa Döndü',
    category: 'restock',
    tag: 'FOMO',
    tagColor: 'text-cyan-400',
    desc: 'Beklenen ürün geri geldi',
    rate: '%35 dönüşüm',
    accent: '#06b6d4',
    heroGrad: 'from-[#051620] via-[#0a2535] to-[#051620]',
    pillBg: 'bg-cyan-500/15 text-cyan-400',
    imageUrl: '/templates/restock.png',
    defaultSubject: '⚡ Beklediğiniz ürün stoğa döndü!',
    defaultPrompt: 'Çok beklenen ürünün stoğa döndüğünü bildiren FOMO kampanyası.',
    blocks: [
      { id: 'b1', type: 'hero', c: { headline: '⚡ O Ürün Geri Döndü!', sub: 'Beklediğiniz an geldi — stoklar kısıtlı', badge: 'STOĞA DÖNDÜ', bgColor: '#051620' } },
      { id: 'b2', type: 'text', c: { body: 'Merhaba {{isim}},\n\nHarika haber! İstediğiniz ürün stoğumuza döndü. Ancak stoklar çok kısıtlı ve hızlı tükenecek.\n\nKaçırmadan önce hemen sipariş verin!' } },
      { id: 'b3', type: 'cta', c: { label: '⚡ Hemen Satın Al →', sub: 'Stoklar kısıtlı · Hızlı tükeniyor', color: '#06b6d4' } },
      { id: 'b4', type: 'footer', c: { brand: 'Mağazanız', addr: 'İstanbul, Türkiye', unsub: 'Abonelikten çık' } },
    ],
  },

  /* ── Görsel Şablonlar (t01–t21) ── */
  {
    id: 't01', name: 'Sepet Hatırlatma', category: 'cart', tag: 'Popüler', tagColor: 'text-amber-400',
    desc: 'Minimalist sepet terk tasarımı', rate: '%34 dönüşüm', accent: '#3b82f6',
    heroGrad: 'from-[#0a1628] via-[#0d1f3c] to-[#0a1628]', pillBg: 'bg-blue-500/15 text-blue-400',
    imageUrl: '/templates/t01.jpeg',
    defaultSubject: 'Sepetiniz sizi bekliyor 🛒', defaultPrompt: 'Sepeti terk eden müşteriler için hatırlatma kampanyası.',
    blocks: [{ id: 'b1', type: 'hero', c: { headline: 'Sepetiniz Sizi Bekliyor', sub: 'Hemen tamamlayın', bgColor: '#0a1628' } }, { id: 'b2', type: 'cta', c: { label: 'Sepetime Dön →', color: '#3b82f6' } }, { id: 'b3', type: 'footer', c: { brand: 'Mağazanız', addr: 'İstanbul, Türkiye', unsub: 'Abonelikten çık' } }],
  },
  {
    id: 't02', name: 'VIP Erken Erişim', category: 'vip', tag: 'Premium', tagColor: 'text-amber-400',
    desc: 'Özel üyelere erken erişim fırsatı', rate: '%43 dönüşüm', accent: '#f59e0b',
    heroGrad: 'from-[#1a1000] via-[#2d1c00] to-[#1a1000]', pillBg: 'bg-amber-500/15 text-amber-400',
    imageUrl: '/templates/t02.jpeg', isPremium: true,
    defaultSubject: 'VIP üyemiz, erken erişim fırsatınız var 👑', defaultPrompt: 'VIP müşterilere erken erişim kampanyası.',
    blocks: [{ id: 'b1', type: 'hero', c: { headline: 'Erken Erişim', sub: 'Sadece VIP üyelere özel', bgColor: '#1a1000' } }, { id: 'b2', type: 'cta', c: { label: 'Keşfet →', color: '#f59e0b' } }, { id: 'b3', type: 'footer', c: { brand: 'Mağazanız', addr: 'İstanbul, Türkiye', unsub: 'Abonelikten çık' } }],
  },
  {
    id: 't03', name: 'Yaz Koleksiyonu', category: 'launch', tag: 'Yeni', tagColor: 'text-violet-400',
    desc: 'Yaz sezonu koleksiyon lansmanı', rate: '%29 dönüşüm', accent: '#8b5cf6',
    heroGrad: 'from-[#0f0a28] via-[#1a0f3d] to-[#0f0a28]', pillBg: 'bg-violet-500/15 text-violet-400',
    imageUrl: '/templates/t03.jpeg',
    defaultSubject: 'Yaz koleksiyonu geldi ☀️', defaultPrompt: 'Yaz sezonu koleksiyon lansmanı.',
    blocks: [{ id: 'b1', type: 'hero', c: { headline: 'Yaz Koleksiyonu', sub: 'Bu sezonun en iyi parçaları', bgColor: '#0f0a28' } }, { id: 'b2', type: 'cta', c: { label: 'Koleksiyonu Gör →', color: '#8b5cf6' } }, { id: 'b3', type: 'footer', c: { brand: 'Mağazanız', addr: 'İstanbul, Türkiye', unsub: 'Abonelikten çık' } }],
  },
  {
    id: 't04', name: 'Black Friday', category: 'promo', tag: 'Büyük İndirim', tagColor: 'text-red-400',
    desc: 'Black Friday özel kampanya', rate: '%52 dönüşüm', accent: '#ef4444',
    heroGrad: 'from-[#1a0808] via-[#2d0f0f] to-[#1a0808]', pillBg: 'bg-red-500/15 text-red-400',
    imageUrl: '/templates/t04.jpeg', isPremium: true,
    defaultSubject: '⚫ Black Friday — En büyük indirimler!', defaultPrompt: 'Black Friday büyük indirim kampanyası.',
    blocks: [{ id: 'b1', type: 'hero', c: { headline: 'BLACK FRIDAY', sub: '%70\'e kadar indirim', bgColor: '#0d0000' } }, { id: 'b2', type: 'coupon', c: { code: 'BLACK70', discount: '%70\'e Kadar', expiry: 'Sadece bugün!' } }, { id: 'b3', type: 'cta', c: { label: 'Hemen Al →', color: '#ef4444' } }, { id: 'b4', type: 'footer', c: { brand: 'Mağazanız', addr: 'İstanbul, Türkiye', unsub: 'Abonelikten çık' } }],
  },
  {
    id: 't05', name: 'Sizi Özledik', category: 'winback', tag: 'Geri Kazan', tagColor: 'text-emerald-400',
    desc: 'Kayıp müşteriyi geri çekme', rate: '%21 dönüşüm', accent: '#10b981',
    heroGrad: 'from-[#051a0d] via-[#0a2d18] to-[#051a0d]', pillBg: 'bg-emerald-500/15 text-emerald-400',
    imageUrl: '/templates/t05.jpeg',
    defaultSubject: 'Sizi çok özledik 💚', defaultPrompt: 'Uzun süre alışveriş yapmayan müşteriyi geri kazanma.',
    blocks: [{ id: 'b1', type: 'hero', c: { headline: 'Sizi Özledik!', sub: 'Geri dönmeniz için özel bir hediye', bgColor: '#051a0d' } }, { id: 'b2', type: 'coupon', c: { code: 'GELDIM15', discount: '%15 İndirim', expiry: '7 gün geçerli' } }, { id: 'b3', type: 'cta', c: { label: 'Alışverişe Dön →', color: '#10b981' } }, { id: 'b4', type: 'footer', c: { brand: 'Mağazanız', addr: 'İstanbul, Türkiye', unsub: 'Abonelikten çık' } }],
  },
  {
    id: 't06', name: 'Anneler Günü', category: 'promo', tag: 'Özel Gün', tagColor: 'text-pink-400',
    desc: 'Anneler Günü özel kampanyası', rate: '%47 dönüşüm', accent: '#ec4899',
    heroGrad: 'from-[#1a0814] via-[#2d0f20] to-[#1a0814]', pillBg: 'bg-pink-500/15 text-pink-400',
    imageUrl: '/templates/t06.jpeg', isPremium: true,
    defaultSubject: '💐 Anneler Günü\'nde annenize özel hediye!', defaultPrompt: 'Anneler Günü kampanyası.',
    blocks: [{ id: 'b1', type: 'hero', c: { headline: 'Anneler Günü Özel', sub: 'Ona en güzel hediyeyi verin', bgColor: '#1a0814' } }, { id: 'b2', type: 'cta', c: { label: 'Hediyeleri Gör →', color: '#ec4899' } }, { id: 'b3', type: 'footer', c: { brand: 'Mağazanız', addr: 'İstanbul, Türkiye', unsub: 'Abonelikten çık' } }],
  },
  {
    id: 't07', name: 'Yeni Üye Kuponu', category: 'welcome', tag: 'Hoş Geldin', tagColor: 'text-teal-400',
    desc: 'İlk alışverişe özel indirim', rate: '%39 dönüşüm', accent: '#059669',
    heroGrad: 'from-[#031a14] via-[#052d20] to-[#031a14]', pillBg: 'bg-teal-500/15 text-teal-400',
    imageUrl: '/templates/t07.jpeg',
    defaultSubject: '🎁 İlk alışverişine özel hediye!', defaultPrompt: 'Yeni üye karşılama kuponu kampanyası.',
    blocks: [{ id: 'b1', type: 'hero', c: { headline: 'Hoş Geldiniz!', sub: 'İlk alışverişe özel indirim', bgColor: '#031a14' } }, { id: 'b2', type: 'coupon', c: { code: 'ILK10', discount: '%10 İndirim', expiry: '30 gün geçerli' } }, { id: 'b3', type: 'cta', c: { label: 'Alışverişe Başla →', color: '#059669' } }, { id: 'b4', type: 'footer', c: { brand: 'Mağazanız', addr: 'İstanbul, Türkiye', unsub: 'Abonelikten çık' } }],
  },
  {
    id: 't08', name: 'Sınırlı Stok', category: 'restock', tag: 'FOMO', tagColor: 'text-cyan-400',
    desc: 'Son birkaç ürün kaldı uyarısı', rate: '%36 dönüşüm', accent: '#06b6d4',
    heroGrad: 'from-[#051620] via-[#0a2535] to-[#051620]', pillBg: 'bg-cyan-500/15 text-cyan-400',
    imageUrl: '/templates/t08.jpeg',
    defaultSubject: '⚠️ Son birkaç adet kaldı!', defaultPrompt: 'Sınırlı stok FOMO kampanyası.',
    blocks: [{ id: 'b1', type: 'hero', c: { headline: 'Son Birkaç Adet!', sub: 'Stoklar tükenmeden önce sipariş verin', bgColor: '#051620' } }, { id: 'b2', type: 'cta', c: { label: '⚡ Hemen Satın Al →', color: '#06b6d4' } }, { id: 'b3', type: 'footer', c: { brand: 'Mağazanız', addr: 'İstanbul, Türkiye', unsub: 'Abonelikten çık' } }],
  },
  {
    id: 't09', name: 'Kış Koleksiyonu', category: 'launch', tag: 'Sezon', tagColor: 'text-blue-400',
    desc: 'Kış sezonu yeni koleksiyon', rate: '%31 dönüşüm', accent: '#3b82f6',
    heroGrad: 'from-[#050f1a] via-[#0a1f35] to-[#050f1a]', pillBg: 'bg-blue-500/15 text-blue-400',
    imageUrl: '/templates/t09.jpeg', isPremium: true,
    defaultSubject: '❄️ Kış koleksiyonu geldi!', defaultPrompt: 'Kış sezonu koleksiyon lansmanı.',
    blocks: [{ id: 'b1', type: 'hero', c: { headline: 'Kış Koleksiyonu', sub: 'Soğuk günler için sıcak parçalar', bgColor: '#050f1a' } }, { id: 'b2', type: 'cta', c: { label: 'Koleksiyonu Gör →', color: '#3b82f6' } }, { id: 'b3', type: 'footer', c: { brand: 'Mağazanız', addr: 'İstanbul, Türkiye', unsub: 'Abonelikten çık' } }],
  },
  {
    id: 't10', name: 'Referans Programı', category: 'welcome', tag: 'Kazan', tagColor: 'text-lime-400',
    desc: 'Arkadaşını davet et, kazan', rate: '%27 dönüşüm', accent: '#84cc16',
    heroGrad: 'from-[#0a1a05] via-[#112a07] to-[#0a1a05]', pillBg: 'bg-lime-500/15 text-lime-400',
    imageUrl: '/templates/t10.jpeg',
    defaultSubject: '🤝 Arkadaşını davet et, ikisi de kazan!', defaultPrompt: 'Referans programı kampanyası.',
    blocks: [{ id: 'b1', type: 'hero', c: { headline: 'Arkadaşını Davet Et', sub: 'Her ikiniz de kazanın', bgColor: '#0a1a05' } }, { id: 'b2', type: 'coupon', c: { code: 'REFERAL20', discount: '%20 İndirim', expiry: 'Her ikisine de' } }, { id: 'b3', type: 'cta', c: { label: 'Davet Et →', color: '#84cc16' } }, { id: 'b4', type: 'footer', c: { brand: 'Mağazanız', addr: 'İstanbul, Türkiye', unsub: 'Abonelikten çık' } }],
  },
  {
    id: 't11', name: 'Süper İndirim', category: 'promo', tag: 'Acil', tagColor: 'text-orange-400',
    desc: '48 saat süper indirim fırsatı', rate: '%41 dönüşüm', accent: '#f97316',
    heroGrad: 'from-[#1a0d05] via-[#2d1a08] to-[#1a0d05]', pillBg: 'bg-orange-500/15 text-orange-400',
    imageUrl: '/templates/t11.jpeg', isPremium: true,
    defaultSubject: '🔥 48 saat süper indirim!', defaultPrompt: '48 saatlik süper indirim kampanyası.',
    blocks: [{ id: 'b1', type: 'hero', c: { headline: 'Süper İndirim!', sub: 'Sadece 48 saat', bgColor: '#1a0d05' } }, { id: 'b2', type: 'coupon', c: { code: 'SUPER25', discount: '%25 İndirim', expiry: '48 saat!' } }, { id: 'b3', type: 'cta', c: { label: 'Hemen Al →', color: '#f97316' } }, { id: 'b4', type: 'footer', c: { brand: 'Mağazanız', addr: 'İstanbul, Türkiye', unsub: 'Abonelikten çık' } }],
  },
  {
    id: 't12', name: 'Sadakat Ödülü', category: 'vip', tag: 'Ödül', tagColor: 'text-yellow-400',
    desc: 'Sadık müşterilere özel puan ödülü', rate: '%38 dönüşüm', accent: '#eab308',
    heroGrad: 'from-[#1a1500] via-[#2d2300] to-[#1a1500]', pillBg: 'bg-yellow-500/15 text-yellow-400',
    imageUrl: '/templates/t12.jpeg', isPremium: true,
    defaultSubject: '⭐ Sadakat puanlarınız hazır!', defaultPrompt: 'Sadakat programı ödül kampanyası.',
    blocks: [{ id: 'b1', type: 'hero', c: { headline: 'Ödülleriniz Hazır!', sub: 'Sadakat puanlarınızı kullanın', bgColor: '#1a1500' } }, { id: 'b2', type: 'coupon', c: { code: 'SADAKAT', discount: '500 Puan = %10', expiry: 'Bu ay geçerli' } }, { id: 'b3', type: 'cta', c: { label: 'Puanlarımı Kullan →', color: '#eab308' } }, { id: 'b4', type: 'footer', c: { brand: 'Mağazanız', addr: 'İstanbul, Türkiye', unsub: 'Abonelikten çık' } }],
  },
  {
    id: 't13', name: 'Yılbaşı Kampanyası', category: 'promo', tag: 'Özel Gün', tagColor: 'text-red-400',
    desc: 'Yeni yıl özel indirim ve hediye', rate: '%45 dönüşüm', accent: '#ef4444',
    heroGrad: 'from-[#1a0505] via-[#2d0808] to-[#1a0505]', pillBg: 'bg-red-500/15 text-red-400',
    imageUrl: '/templates/t13.jpeg', isPremium: true,
    defaultSubject: '🎉 Yeni yılda büyük indirim!', defaultPrompt: 'Yılbaşı özel kampanyası.',
    blocks: [{ id: 'b1', type: 'hero', c: { headline: 'Yeni Yıl Özel!', sub: 'Yeni yılı indirimle karşılayın', bgColor: '#1a0505' } }, { id: 'b2', type: 'coupon', c: { code: 'YILBASI30', discount: '%30 İndirim', expiry: '31 Aralık\'a kadar' } }, { id: 'b3', type: 'cta', c: { label: 'Fırsatı Yakala →', color: '#ef4444' } }, { id: 'b4', type: 'footer', c: { brand: 'Mağazanız', addr: 'İstanbul, Türkiye', unsub: 'Abonelikten çık' } }],
  },
  {
    id: 't14', name: 'Abonelik Yenile', category: 'vip', tag: 'Hatırlatma', tagColor: 'text-violet-400',
    desc: 'Abonelik yenileme hatırlatması', rate: '%62 dönüşüm', accent: '#7c3aed',
    heroGrad: 'from-[#0f0520] via-[#1a0935] to-[#0f0520]', pillBg: 'bg-violet-500/15 text-violet-400',
    imageUrl: '/templates/t14.jpeg', isPremium: true,
    defaultSubject: '⚡ Aboneliğiniz sona eriyor!', defaultPrompt: 'Abonelik yenileme hatırlatma kampanyası.',
    blocks: [{ id: 'b1', type: 'hero', c: { headline: 'Aboneliğiniz Bitiyor', sub: 'Yenileyin ve avantajları kaybetmeyin', bgColor: '#0f0520' } }, { id: 'b2', type: 'coupon', c: { code: 'YENILE10', discount: '%10 Yenileme İndirimi', expiry: 'Son 3 gün!' } }, { id: 'b3', type: 'cta', c: { label: 'Şimdi Yenile →', color: '#7c3aed' } }, { id: 'b4', type: 'footer', c: { brand: 'Mağazanız', addr: 'İstanbul, Türkiye', unsub: 'Abonelikten çık' } }],
  },
  {
    id: 't15', name: 'Yeni Ürün Bildirimi', category: 'restock', tag: 'Bildirim', tagColor: 'text-sky-400',
    desc: 'Bekleme listesindeki ürün geldi', rate: '%58 dönüşüm', accent: '#0ea5e9',
    heroGrad: 'from-[#051520] via-[#082535] to-[#051520]', pillBg: 'bg-sky-500/15 text-sky-400',
    imageUrl: '/templates/t15.jpeg',
    defaultSubject: '✅ Beklediğiniz ürün geldi!', defaultPrompt: 'Bekleme listesi ürün geldi bildirimi.',
    blocks: [{ id: 'b1', type: 'hero', c: { headline: 'Ürününüz Geldi!', sub: 'Bekleme listenizden ürün stokta', bgColor: '#051520' } }, { id: 'b2', type: 'cta', c: { label: 'Hemen Sipariş Ver →', color: '#0ea5e9' } }, { id: 'b3', type: 'footer', c: { brand: 'Mağazanız', addr: 'İstanbul, Türkiye', unsub: 'Abonelikten çık' } }],
  },
  {
    id: 't16', name: 'Premium Koleksiyon', category: 'launch', tag: 'Lüks', tagColor: 'text-amber-400',
    desc: 'Premium segment yeni koleksiyon', rate: '%33 dönüşüm', accent: '#d97706',
    heroGrad: 'from-[#1a1000] via-[#2d1c00] to-[#1a1000]', pillBg: 'bg-amber-500/15 text-amber-400',
    imageUrl: '/templates/t16.jpeg', isPremium: true,
    defaultSubject: '👑 Premium koleksiyon — sadece seçkin müşterilerimize', defaultPrompt: 'Premium lüks koleksiyon lansmanı.',
    blocks: [{ id: 'b1', type: 'hero', c: { headline: 'Premium Koleksiyon', sub: 'En seçkin parçalar, sizin için', bgColor: '#1a1000' } }, { id: 'b2', type: 'cta', c: { label: 'Koleksiyonu Keşfet →', color: '#d97706' } }, { id: 'b3', type: 'footer', c: { brand: 'Mağazanız', addr: 'İstanbul, Türkiye', unsub: 'Abonelikten çık' } }],
  },
  {
    id: 't17', name: 'Ücretsiz Kargo', category: 'promo', tag: 'Fırsat', tagColor: 'text-green-400',
    desc: 'Ücretsiz kargo kampanyası', rate: '%44 dönüşüm', accent: '#22c55e',
    heroGrad: 'from-[#051a0a] via-[#0a2d12] to-[#051a0a]', pillBg: 'bg-green-500/15 text-green-400',
    imageUrl: '/templates/t17.jpeg',
    defaultSubject: '🚚 Tüm siparişlerde ücretsiz kargo!', defaultPrompt: 'Ücretsiz kargo kampanyası.',
    blocks: [{ id: 'b1', type: 'hero', c: { headline: 'Ücretsiz Kargo!', sub: 'Minimum tutar olmadan tüm siparişlerde', bgColor: '#051a0a' } }, { id: 'b2', type: 'coupon', c: { code: 'FREESHIP', discount: 'Ücretsiz Kargo', expiry: 'Bu hafta sonu!' } }, { id: 'b3', type: 'cta', c: { label: 'Alışverişe Başla →', color: '#22c55e' } }, { id: 'b4', type: 'footer', c: { brand: 'Mağazanız', addr: 'İstanbul, Türkiye', unsub: 'Abonelikten çık' } }],
  },
  {
    id: 't18', name: 'Doğum Günü VIP', category: 'birthday', tag: 'Kişisel', tagColor: 'text-rose-400',
    desc: 'VIP üyeler için özel doğum günü', rate: '%51 dönüşüm', accent: '#f43f5e',
    heroGrad: 'from-[#1a0510] via-[#2d0818] to-[#1a0510]', pillBg: 'bg-rose-500/15 text-rose-400',
    imageUrl: '/templates/t18.jpeg', isPremium: true,
    defaultSubject: '🎂 Doğum günün kutlu olsun, sürprizin hazır!', defaultPrompt: 'VIP müşteri doğum günü özel kampanyası.',
    blocks: [{ id: 'b1', type: 'hero', c: { headline: 'Mutlu Yıllar!', sub: 'Bu özel gün için sürprizin var', bgColor: '#1a0510' } }, { id: 'b2', type: 'coupon', c: { code: 'DOGUMGUN25', discount: '%25 Özel İndirim 🎁', expiry: '3 gün geçerli' } }, { id: 'b3', type: 'cta', c: { label: 'Hediyeni Al →', color: '#f43f5e' } }, { id: 'b4', type: 'footer', c: { brand: 'Mağazanız', addr: 'İstanbul, Türkiye', unsub: 'Abonelikten çık' } }],
  },
  {
    id: 't19', name: 'Çift Puan Haftası', category: 'vip', tag: 'Ödül', tagColor: 'text-indigo-400',
    desc: 'Çift puan kazanma haftası', rate: '%35 dönüşüm', accent: '#6366f1',
    heroGrad: 'from-[#080520] via-[#100a35] to-[#080520]', pillBg: 'bg-indigo-500/15 text-indigo-400',
    imageUrl: '/templates/t19.jpeg', isPremium: true,
    defaultSubject: '⭐⭐ Bu hafta çift puan!', defaultPrompt: 'Çift puan kazanma haftası kampanyası.',
    blocks: [{ id: 'b1', type: 'hero', c: { headline: 'Çift Puan Haftası!', sub: 'Tüm alışverişlerden 2x puan', bgColor: '#080520' } }, { id: 'b2', type: 'cta', c: { label: 'Puan Kazan →', color: '#6366f1' } }, { id: 'b3', type: 'footer', c: { brand: 'Mağazanız', addr: 'İstanbul, Türkiye', unsub: 'Abonelikten çık' } }],
  },
  {
    id: 't20', name: 'Son Fırsat', category: 'cart', tag: 'Acil', tagColor: 'text-red-400',
    desc: 'Sepetteki ürün fiyatı değişiyor', rate: '%29 dönüşüm', accent: '#dc2626',
    heroGrad: 'from-[#1a0505] via-[#2d0808] to-[#1a0505]', pillBg: 'bg-red-500/15 text-red-400',
    imageUrl: '/templates/t20.jpeg',
    defaultSubject: '⏰ Sepetinizdeki ürünün fiyatı değişiyor!', defaultPrompt: 'Fiyat değişim uyarısı sepet terk kampanyası.',
    blocks: [{ id: 'b1', type: 'hero', c: { headline: 'Son Fırsat!', sub: 'Fiyat değişmeden önce al', bgColor: '#1a0505' } }, { id: 'b2', type: 'cta', c: { label: 'Şimdi Satın Al →', color: '#dc2626' } }, { id: 'b3', type: 'footer', c: { brand: 'Mağazanız', addr: 'İstanbul, Türkiye', unsub: 'Abonelikten çık' } }],
  },
  {
    id: 't21', name: 'Özel Koleksiyon', category: 'launch', tag: 'Özel', tagColor: 'text-fuchsia-400',
    desc: 'Sınırlı sayıda özel koleksiyon', rate: '%37 dönüşüm', accent: '#a855f7',
    heroGrad: 'from-[#150520] via-[#220835] to-[#150520]', pillBg: 'bg-fuchsia-500/15 text-fuchsia-400',
    imageUrl: '/templates/t21.jpeg', isPremium: true,
    defaultSubject: '✨ Sınırlı sayıda özel koleksiyon', defaultPrompt: 'Sınırlı sayıda özel koleksiyon lansmanı.',
    blocks: [{ id: 'b1', type: 'hero', c: { headline: 'Özel Koleksiyon', sub: 'Sınırlı sayıda, sadece seçkinlere', bgColor: '#150520' } }, { id: 'b2', type: 'cta', c: { label: 'Hemen İncele →', color: '#a855f7' } }, { id: 'b3', type: 'footer', c: { brand: 'Mağazanız', addr: 'İstanbul, Türkiye', unsub: 'Abonelikten çık' } }],
  },
]

export function getPresetById(id: string): TemplatePreset | undefined {
  return templatePresets.find(t => t.id === id)
}
