import type { Template } from './types'

export const TEMPLATES: Template[] = [
  {
    id: 'summer-sale',
    name: 'Yaz İndirimi',
    category: 'Sezonsal',
    previewGradient: 'linear-gradient(135deg, #1a0a2e 0%, #2d1b69 50%, #ff6b35 100%)',
    canvasWidth: 600,
    canvasHeight: 400,
    layers: [
      {
        id: 'bg', type: 'background', label: 'Arka Plan', x: 0, y: 0,
        width: 600, height: 400, rotation: 0, zIndex: 0,
        editable: true, locked: false, visible: true,
        style: { gradientFrom: '#1a0a2e', gradientTo: '#2d1b69', gradientAngle: 135 },
      },
      {
        id: 'shape-circle', type: 'shape', label: 'Dekoratif Daire', x: 420, y: 260,
        width: 200, height: 200, rotation: 0, zIndex: 1,
        editable: true, locked: false, visible: true,
        style: { fill: 'rgba(255,107,53,0.15)', stroke: 'rgba(255,107,53,0.3)', strokeWidth: 1 },
      },
      {
        id: 'shape-circle2', type: 'shape', label: 'Dekoratif Daire 2', x: -40, y: 250,
        width: 160, height: 160, rotation: 0, zIndex: 1,
        editable: false, locked: true, visible: true,
        style: { fill: 'rgba(153,180,255,0.08)', stroke: 'rgba(153,180,255,0.15)', strokeWidth: 1 },
      },
      {
        id: 'product', type: 'productImage', label: 'Ürün Görseli', x: 360, y: 30,
        width: 210, height: 300, rotation: 0, zIndex: 3,
        editable: true, locked: false, visible: true,
        style: { opacity: 1 },
      },
      {
        id: 'badge', type: 'badge', label: 'Rozet', x: 28, y: 28,
        width: 130, height: 30, rotation: 0, zIndex: 4,
        editable: true, locked: false, visible: true,
        content: '🌞 YAZ SEZONU',
        style: { fill: 'rgba(255,107,53,0.2)', color: '#ff8c5a', fontSize: 11, fontWeight: '700',
          letterSpacing: 1.5, borderRadius: 20, stroke: 'rgba(255,107,53,0.4)', strokeWidth: 1, uppercase: true },
      },
      {
        id: 'headline', type: 'headline', label: 'Ana Başlık', x: 28, y: 80,
        width: 300, height: 80, rotation: 0, zIndex: 4,
        editable: true, locked: false, visible: true,
        content: 'Yaz Koleksiyonu\nÇok Yakında',
        style: { color: '#eeeef4', fontSize: 36, fontWeight: '800', lineHeight: 1.2, fontFamily: 'Inter' },
      },
      {
        id: 'subheadline', type: 'subheadline', label: 'Alt Başlık', x: 28, y: 180,
        width: 280, height: 40, rotation: 0, zIndex: 4,
        editable: true, locked: false, visible: true,
        content: 'Özel seçilmiş ürünler, özel fiyatlar',
        style: { color: '#8080a0', fontSize: 14, fontWeight: '400', fontFamily: 'Inter' },
      },
      {
        id: 'price', type: 'price', label: 'Fiyat / İndirim', x: 28, y: 232,
        width: 160, height: 50, rotation: 0, zIndex: 4,
        editable: true, locked: false, visible: true,
        content: '%40\'a Kadar İndirim',
        style: { color: '#ff8c5a', fontSize: 18, fontWeight: '700', fontFamily: 'Inter' },
      },
      {
        id: 'cta', type: 'ctaButton', label: 'CTA Butonu', x: 28, y: 306,
        width: 180, height: 44, rotation: 0, zIndex: 5,
        editable: true, locked: false, visible: true,
        content: 'Şimdi Alışveriş Yap',
        style: { fill: '#ff6b35', color: '#ffffff', fontSize: 13, fontWeight: '700',
          borderRadius: 22, paddingX: 24, paddingY: 12, fontFamily: 'Inter' },
      },
    ],
  },

  {
    id: 'cart-abandon',
    name: 'Sepet Hatırlatma',
    category: 'Dönüşüm',
    previewGradient: 'linear-gradient(135deg, #0a0a14 0%, #0f1a2e 50%, #1a2a4a 100%)',
    canvasWidth: 600,
    canvasHeight: 400,
    layers: [
      {
        id: 'bg', type: 'background', label: 'Arka Plan', x: 0, y: 0,
        width: 600, height: 400, rotation: 0, zIndex: 0,
        editable: true, locked: false, visible: true,
        style: { gradientFrom: '#0a0a14', gradientTo: '#1a2a4a', gradientAngle: 135 },
      },
      {
        id: 'product', type: 'productImage', label: 'Ürün Görseli', x: 340, y: 20,
        width: 230, height: 320, rotation: -3, zIndex: 2,
        editable: true, locked: false, visible: true,
        style: { opacity: 1 },
      },
      {
        id: 'urgency-badge', type: 'badge', label: 'Aciliyet Rozeti', x: 28, y: 28,
        width: 160, height: 32, rotation: 0, zIndex: 4,
        editable: true, locked: false, visible: true,
        content: '⏰ STOK AZALIYOR',
        style: { fill: 'rgba(232,69,69,0.15)', color: '#e84545', fontSize: 11, fontWeight: '700',
          borderRadius: 20, stroke: 'rgba(232,69,69,0.35)', strokeWidth: 1, letterSpacing: 1 },
      },
      {
        id: 'headline', type: 'headline', label: 'Ana Başlık', x: 28, y: 82,
        width: 290, height: 90, rotation: 0, zIndex: 4,
        editable: true, locked: false, visible: true,
        content: 'Sepetiniz\nSizi Bekliyor',
        style: { color: '#eeeef4', fontSize: 38, fontWeight: '800', lineHeight: 1.15, fontFamily: 'Inter' },
      },
      {
        id: 'subheadline', type: 'subheadline', label: 'Alt Başlık', x: 28, y: 188,
        width: 275, height: 40, rotation: 0, zIndex: 4,
        editable: true, locked: false, visible: true,
        content: 'Seçtiğiniz ürünler hâlâ mevcut',
        style: { color: '#666680', fontSize: 14, fontWeight: '400', fontFamily: 'Inter' },
      },
      {
        id: 'price', type: 'price', label: 'İndirim', x: 28, y: 240,
        width: 220, height: 42, rotation: 0, zIndex: 4,
        editable: true, locked: false, visible: true,
        content: 'Bugün özel %15 indirim!',
        style: { color: '#22c97a', fontSize: 16, fontWeight: '700', fontFamily: 'Inter' },
      },
      {
        id: 'cta', type: 'ctaButton', label: 'CTA Butonu', x: 28, y: 306,
        width: 200, height: 46, rotation: 0, zIndex: 5,
        editable: true, locked: false, visible: true,
        content: 'Sepete Dön →',
        style: { fill: '#4470ff', color: '#ffffff', fontSize: 14, fontWeight: '700',
          borderRadius: 23, paddingX: 28, paddingY: 13, fontFamily: 'Inter' },
      },
    ],
  },

  {
    id: 'vip-campaign',
    name: 'VIP Kampanya',
    category: 'Sadakat',
    previewGradient: 'linear-gradient(135deg, #0a0808 0%, #1a1008 50%, #2a1e00 100%)',
    canvasWidth: 600,
    canvasHeight: 400,
    layers: [
      {
        id: 'bg', type: 'background', label: 'Arka Plan', x: 0, y: 0,
        width: 600, height: 400, rotation: 0, zIndex: 0,
        editable: true, locked: false, visible: true,
        style: { gradientFrom: '#0a0808', gradientTo: '#1e1600', gradientAngle: 135 },
      },
      {
        id: 'gold-line', type: 'shape', label: 'Altın Çizgi', x: 0, y: 0,
        width: 600, height: 3, rotation: 0, zIndex: 1,
        editable: false, locked: true, visible: true,
        style: { fill: '#d4a017', gradientFrom: 'transparent', gradientTo: '#d4a017' },
      },
      {
        id: 'product', type: 'productImage', label: 'Ürün Görseli', x: 350, y: 30,
        width: 220, height: 300, rotation: 0, zIndex: 2,
        editable: true, locked: false, visible: true,
        style: { opacity: 1 },
      },
      {
        id: 'badge', type: 'badge', label: 'VIP Rozeti', x: 28, y: 28,
        width: 100, height: 30, rotation: 0, zIndex: 4,
        editable: true, locked: false, visible: true,
        content: '★ VIP ÜYE',
        style: { fill: 'rgba(212,160,23,0.12)', color: '#d4a017', fontSize: 11, fontWeight: '700',
          borderRadius: 20, stroke: 'rgba(212,160,23,0.3)', strokeWidth: 1, letterSpacing: 2 },
      },
      {
        id: 'headline', type: 'headline', label: 'Ana Başlık', x: 28, y: 82,
        width: 295, height: 90, rotation: 0, zIndex: 4,
        editable: true, locked: false, visible: true,
        content: 'Sadece Sizin\nİçin Özel',
        style: { color: '#eeeef4', fontSize: 38, fontWeight: '800', lineHeight: 1.15, fontFamily: 'Inter' },
      },
      {
        id: 'subheadline', type: 'subheadline', label: 'Alt Başlık', x: 28, y: 188,
        width: 275, height: 40, rotation: 0, zIndex: 4,
        editable: true, locked: false, visible: true,
        content: 'VIP üyelerimize özel erken erişim',
        style: { color: '#8080a0', fontSize: 14, fontWeight: '400', fontFamily: 'Inter' },
      },
      {
        id: 'price', type: 'price', label: 'Fiyat', x: 28, y: 240,
        width: 200, height: 42, rotation: 0, zIndex: 4,
        editable: true, locked: false, visible: true,
        content: '₺2.499 → ₺1.749',
        style: { color: '#d4a017', fontSize: 20, fontWeight: '800', fontFamily: 'Inter' },
      },
      {
        id: 'cta', type: 'ctaButton', label: 'CTA Butonu', x: 28, y: 308,
        width: 185, height: 44, rotation: 0, zIndex: 5,
        editable: true, locked: false, visible: true,
        content: 'Özel Teklife Bak',
        style: { fill: '#d4a017', color: '#0a0808', fontSize: 13, fontWeight: '800',
          borderRadius: 22, paddingX: 24, paddingY: 12, fontFamily: 'Inter' },
      },
    ],
  },

  {
    id: 'product-launch',
    name: 'Ürün Lansmanı',
    category: 'Lansman',
    previewGradient: 'linear-gradient(135deg, #08080f 0%, #0f0f1a 50%, #1a1030 100%)',
    canvasWidth: 600,
    canvasHeight: 400,
    layers: [
      {
        id: 'bg', type: 'background', label: 'Arka Plan', x: 0, y: 0,
        width: 600, height: 400, rotation: 0, zIndex: 0,
        editable: true, locked: false, visible: true,
        style: { gradientFrom: '#08080f', gradientTo: '#151530', gradientAngle: 160 },
      },
      {
        id: 'glow', type: 'shape', label: 'Işık Efekti', x: 280, y: 60,
        width: 240, height: 240, rotation: 0, zIndex: 1,
        editable: false, locked: true, visible: true,
        style: { fill: 'rgba(68,112,255,0.07)' },
      },
      {
        id: 'product', type: 'productImage', label: 'Ürün Görseli', x: 330, y: 20,
        width: 240, height: 320, rotation: 0, zIndex: 3,
        editable: true, locked: false, visible: true,
        style: { opacity: 1 },
      },
      {
        id: 'badge', type: 'badge', label: 'Yeni Rozet', x: 28, y: 28,
        width: 90, height: 28, rotation: 0, zIndex: 4,
        editable: true, locked: false, visible: true,
        content: '✦ YENİ',
        style: { fill: 'rgba(68,112,255,0.15)', color: '#4470ff', fontSize: 11, fontWeight: '700',
          borderRadius: 14, stroke: 'rgba(68,112,255,0.3)', strokeWidth: 1, letterSpacing: 2 },
      },
      {
        id: 'headline', type: 'headline', label: 'Ana Başlık', x: 28, y: 78,
        width: 285, height: 100, rotation: 0, zIndex: 4,
        editable: true, locked: false, visible: true,
        content: 'Yeni Sezon\nGeliyor',
        style: { color: '#eeeef4', fontSize: 40, fontWeight: '800', lineHeight: 1.1, fontFamily: 'Inter' },
      },
      {
        id: 'subheadline', type: 'subheadline', label: 'Alt Başlık', x: 28, y: 196,
        width: 270, height: 36, rotation: 0, zIndex: 4,
        editable: true, locked: false, visible: true,
        content: 'İlk 100 siparişe ücretsiz kargo',
        style: { color: '#666680', fontSize: 13, fontWeight: '400', fontFamily: 'Inter' },
      },
      {
        id: 'price', type: 'price', label: 'Lansman Fiyatı', x: 28, y: 244,
        width: 200, height: 40, rotation: 0, zIndex: 4,
        editable: true, locked: false, visible: true,
        content: 'Lansman fiyatı ₺899',
        style: { color: '#99b4ff', fontSize: 16, fontWeight: '700', fontFamily: 'Inter' },
      },
      {
        id: 'cta', type: 'ctaButton', label: 'CTA Butonu', x: 28, y: 308,
        width: 175, height: 44, rotation: 0, zIndex: 5,
        editable: true, locked: false, visible: true,
        content: 'Şimdi İncele',
        style: { fill: '#4470ff', color: '#ffffff', fontSize: 14, fontWeight: '700',
          borderRadius: 22, paddingX: 28, paddingY: 13, fontFamily: 'Inter' },
      },
    ],
  },

  {
    id: 'black-friday',
    name: 'Black Friday',
    category: 'Kampanya',
    previewGradient: 'linear-gradient(135deg, #000000 0%, #0a0500 50%, #1a0800 100%)',
    canvasWidth: 600,
    canvasHeight: 400,
    layers: [
      {
        id: 'bg', type: 'background', label: 'Arka Plan', x: 0, y: 0,
        width: 600, height: 400, rotation: 0, zIndex: 0,
        editable: true, locked: false, visible: true,
        style: { fill: '#000000' },
      },
      {
        id: 'accent-bar', type: 'shape', label: 'Aksent Çizgi', x: 0, y: 0,
        width: 600, height: 4, rotation: 0, zIndex: 1,
        editable: false, locked: true, visible: true,
        style: { fill: '#f59e0b' },
      },
      {
        id: 'product', type: 'productImage', label: 'Ürün Görseli', x: 340, y: 28,
        width: 230, height: 310, rotation: 0, zIndex: 2,
        editable: true, locked: false, visible: true,
        style: { opacity: 1 },
      },
      {
        id: 'badge', type: 'badge', label: 'BF Rozet', x: 28, y: 28,
        width: 145, height: 32, rotation: 0, zIndex: 4,
        editable: true, locked: false, visible: true,
        content: '⚡ BLACK FRIDAY',
        style: { fill: '#f59e0b', color: '#000000', fontSize: 11, fontWeight: '900',
          borderRadius: 4, letterSpacing: 1.5 },
      },
      {
        id: 'headline', type: 'headline', label: 'Ana Başlık', x: 28, y: 84,
        width: 290, height: 90, rotation: 0, zIndex: 4,
        editable: true, locked: false, visible: true,
        content: 'Yılın En\nBüyük İndirimi',
        style: { color: '#ffffff', fontSize: 36, fontWeight: '900', lineHeight: 1.15, fontFamily: 'Inter' },
      },
      {
        id: 'price', type: 'price', label: 'İndirim Oranı', x: 28, y: 192,
        width: 180, height: 70, rotation: 0, zIndex: 4,
        editable: true, locked: false, visible: true,
        content: '%70\nİNDİRİM',
        style: { color: '#f59e0b', fontSize: 44, fontWeight: '900', lineHeight: 1.0, fontFamily: 'Inter' },
      },
      {
        id: 'subheadline', type: 'subheadline', label: 'Alt Başlık', x: 28, y: 278,
        width: 260, height: 32, rotation: 0, zIndex: 4,
        editable: true, locked: false, visible: true,
        content: 'Sadece 24 saat geçerli',
        style: { color: '#888888', fontSize: 13, fontFamily: 'Inter' },
      },
      {
        id: 'cta', type: 'ctaButton', label: 'CTA Butonu', x: 28, y: 328,
        width: 190, height: 46, rotation: 0, zIndex: 5,
        editable: true, locked: false, visible: true,
        content: 'Fırsatı Yakala →',
        style: { fill: '#f59e0b', color: '#000000', fontSize: 14, fontWeight: '900',
          borderRadius: 4, paddingX: 24, paddingY: 13, fontFamily: 'Inter' },
      },
    ],
  },

  {
    id: 'welcome',
    name: 'Hoş Geldin',
    category: 'Otomasyon',
    previewGradient: 'linear-gradient(135deg, #0d1117 0%, #0f1a2e 50%, #162040 100%)',
    canvasWidth: 600,
    canvasHeight: 400,
    layers: [
      {
        id: 'bg', type: 'background', label: 'Arka Plan', x: 0, y: 0,
        width: 600, height: 400, rotation: 0, zIndex: 0,
        editable: true, locked: false, visible: true,
        style: { gradientFrom: '#0d1117', gradientTo: '#162040', gradientAngle: 135 },
      },
      {
        id: 'product', type: 'productImage', label: 'Ürün / Logo', x: 370, y: 40,
        width: 200, height: 280, rotation: 0, zIndex: 2,
        editable: true, locked: false, visible: true,
        style: { opacity: 1 },
      },
      {
        id: 'badge', type: 'badge', label: 'Karşılama Rozeti', x: 28, y: 28,
        width: 130, height: 28, rotation: 0, zIndex: 4,
        editable: true, locked: false, visible: true,
        content: '👋 HOŞ GELDİNİZ',
        style: { fill: 'rgba(34,201,122,0.12)', color: '#22c97a', fontSize: 10, fontWeight: '700',
          borderRadius: 14, stroke: 'rgba(34,201,122,0.25)', strokeWidth: 1, letterSpacing: 1.5 },
      },
      {
        id: 'headline', type: 'headline', label: 'Ana Başlık', x: 28, y: 78,
        width: 315, height: 90, rotation: 0, zIndex: 4,
        editable: true, locked: false, visible: true,
        content: 'Ailemize\nHoş Geldiniz',
        style: { color: '#eeeef4', fontSize: 38, fontWeight: '800', lineHeight: 1.15, fontFamily: 'Inter' },
      },
      {
        id: 'subheadline', type: 'subheadline', label: 'Alt Başlık', x: 28, y: 185,
        width: 295, height: 50, rotation: 0, zIndex: 4,
        editable: true, locked: false, visible: true,
        content: 'Sizin için özel hazırladığımız koleksiyona göz atın',
        style: { color: '#666680', fontSize: 13, fontWeight: '400', lineHeight: 1.5, fontFamily: 'Inter' },
      },
      {
        id: 'price', type: 'price', label: 'İlk Alışveriş İndirimi', x: 28, y: 249,
        width: 250, height: 36, rotation: 0, zIndex: 4,
        editable: true, locked: false, visible: true,
        content: 'İlk siparişinizde %10 indirim',
        style: { color: '#22c97a', fontSize: 14, fontWeight: '700', fontFamily: 'Inter' },
      },
      {
        id: 'cta', type: 'ctaButton', label: 'CTA Butonu', x: 28, y: 310,
        width: 185, height: 44, rotation: 0, zIndex: 5,
        editable: true, locked: false, visible: true,
        content: 'Keşfetmeye Başla',
        style: { fill: '#22c97a', color: '#08080f', fontSize: 13, fontWeight: '800',
          borderRadius: 22, paddingX: 24, paddingY: 12, fontFamily: 'Inter' },
      },
    ],
  },

  {
    id: 'new-collection',
    name: 'Yeni Koleksiyon',
    category: 'Koleksiyon',
    previewGradient: 'linear-gradient(135deg, #0d0520 0%, #1a0a3a 50%, #6b21a8 100%)',
    canvasWidth: 600,
    canvasHeight: 400,
    layers: [
      { id: 'bg', type: 'background', label: 'Arka Plan', x: 0, y: 0, width: 600, height: 400, rotation: 0, zIndex: 0, editable: true, locked: false, visible: true, style: { gradientFrom: '#0d0520', gradientTo: '#4a1070', gradientAngle: 135 } },
      { id: 'glow', type: 'shape', label: 'Işık Efekti', x: 350, y: 80, width: 220, height: 220, rotation: 0, zIndex: 1, editable: false, locked: true, visible: true, style: { fill: 'rgba(168,85,247,0.12)' } },
      { id: 'product', type: 'productImage', label: 'Ürün Görseli', x: 355, y: 20, width: 220, height: 310, rotation: 0, zIndex: 3, editable: true, locked: false, visible: true, style: { opacity: 1 } },
      { id: 'badge', type: 'badge', label: 'Rozet', x: 28, y: 28, width: 150, height: 30, rotation: 0, zIndex: 4, editable: true, locked: false, visible: true, content: '✦ YENİ KOLEKSİYON', style: { fill: 'rgba(168,85,247,0.15)', color: '#c084fc', fontSize: 10, fontWeight: '700', borderRadius: 20, stroke: 'rgba(168,85,247,0.3)', strokeWidth: 1, letterSpacing: 2 } },
      { id: 'headline', type: 'headline', label: 'Ana Başlık', x: 28, y: 80, width: 295, height: 90, rotation: 0, zIndex: 4, editable: true, locked: false, visible: true, content: '2025 İlkbahar\nKoleksiyonu', style: { color: '#f3e8ff', fontSize: 36, fontWeight: '800', lineHeight: 1.15, fontFamily: 'Inter' } },
      { id: 'subheadline', type: 'subheadline', label: 'Alt Başlık', x: 28, y: 188, width: 280, height: 36, rotation: 0, zIndex: 4, editable: true, locked: false, visible: true, content: 'Yeni sezonun öne çıkan parçaları', style: { color: '#9d4edd', fontSize: 13, fontFamily: 'Inter' } },
      { id: 'price', type: 'price', label: 'Fiyat', x: 28, y: 238, width: 200, height: 36, rotation: 0, zIndex: 4, editable: true, locked: false, visible: true, content: 'Erken erişim — ₺1.299\'dan', style: { color: '#e9d5ff', fontSize: 14, fontWeight: '700', fontFamily: 'Inter' } },
      { id: 'cta', type: 'ctaButton', label: 'CTA Butonu', x: 28, y: 310, width: 170, height: 44, rotation: 0, zIndex: 5, editable: true, locked: false, visible: true, content: 'Koleksiyonu Gör', style: { fill: '#7c3aed', color: '#ffffff', fontSize: 13, fontWeight: '700', borderRadius: 22, fontFamily: 'Inter' } },
    ],
  },

  {
    id: 'minimal-luxury',
    name: 'Minimal Luxury',
    category: 'Lüks',
    previewGradient: 'linear-gradient(135deg, #080808 0%, #141414 50%, #1e1c14 100%)',
    canvasWidth: 600,
    canvasHeight: 400,
    layers: [
      { id: 'bg', type: 'background', label: 'Arka Plan', x: 0, y: 0, width: 600, height: 400, rotation: 0, zIndex: 0, editable: true, locked: false, visible: true, style: { fill: '#080808' } },
      { id: 'top-line', type: 'shape', label: 'Üst Çizgi', x: 28, y: 28, width: 544, height: 1, rotation: 0, zIndex: 1, editable: false, locked: true, visible: true, style: { fill: 'rgba(212,175,55,0.4)' } },
      { id: 'bottom-line', type: 'shape', label: 'Alt Çizgi', x: 28, y: 371, width: 544, height: 1, rotation: 0, zIndex: 1, editable: false, locked: true, visible: true, style: { fill: 'rgba(212,175,55,0.4)' } },
      { id: 'product', type: 'productImage', label: 'Ürün Görseli', x: 330, y: 40, width: 240, height: 290, rotation: 0, zIndex: 2, editable: true, locked: false, visible: true, style: { opacity: 1 } },
      { id: 'badge', type: 'badge', label: 'Rozet', x: 40, y: 40, width: 110, height: 24, rotation: 0, zIndex: 4, editable: true, locked: false, visible: true, content: 'MAISON', style: { fill: 'transparent', color: '#d4af37', fontSize: 10, fontWeight: '700', letterSpacing: 5, uppercase: true } },
      { id: 'headline', type: 'headline', label: 'Ana Başlık', x: 40, y: 90, width: 270, height: 100, rotation: 0, zIndex: 4, editable: true, locked: false, visible: true, content: 'Zamansız\nElegance', style: { color: '#f5f5f0', fontSize: 38, fontWeight: '300', lineHeight: 1.1, fontFamily: 'Inter', letterSpacing: -1 } },
      { id: 'subheadline', type: 'subheadline', label: 'Alt Başlık', x: 40, y: 208, width: 260, height: 40, rotation: 0, zIndex: 4, editable: true, locked: false, visible: true, content: 'Özel sipariş, sınırlı üretim', style: { color: '#6b6b5a', fontSize: 12, fontFamily: 'Inter', letterSpacing: 1 } },
      { id: 'price', type: 'price', label: 'Fiyat', x: 40, y: 260, width: 180, height: 30, rotation: 0, zIndex: 4, editable: true, locked: false, visible: true, content: '₺4.850', style: { color: '#d4af37', fontSize: 20, fontWeight: '300', fontFamily: 'Inter', letterSpacing: 2 } },
      { id: 'cta', type: 'ctaButton', label: 'CTA Butonu', x: 40, y: 314, width: 160, height: 40, rotation: 0, zIndex: 5, editable: true, locked: false, visible: true, content: 'Keşfet', style: { fill: 'transparent', color: '#d4af37', fontSize: 11, fontWeight: '400', borderRadius: 0, stroke: '#d4af37', strokeWidth: 1, letterSpacing: 3, fontFamily: 'Inter', uppercase: true } },
    ],
  },

  {
    id: 'tech-product',
    name: 'Teknoloji Ürünü',
    category: 'Teknoloji',
    previewGradient: 'linear-gradient(135deg, #010b1a 0%, #031628 50%, #0a2540 100%)',
    canvasWidth: 600,
    canvasHeight: 400,
    layers: [
      { id: 'bg', type: 'background', label: 'Arka Plan', x: 0, y: 0, width: 600, height: 400, rotation: 0, zIndex: 0, editable: true, locked: false, visible: true, style: { gradientFrom: '#010b1a', gradientTo: '#0a2540', gradientAngle: 135 } },
      { id: 'grid', type: 'shape', label: 'Grid Efekt', x: 0, y: 0, width: 600, height: 400, rotation: 0, zIndex: 1, editable: false, locked: true, visible: true, style: { fill: 'transparent', stroke: 'rgba(0,212,255,0.05)', strokeWidth: 1 } },
      { id: 'glow', type: 'shape', label: 'Neon Işık', x: 280, y: 50, width: 280, height: 280, rotation: 0, zIndex: 1, editable: false, locked: true, visible: true, style: { fill: 'rgba(0,212,255,0.06)' } },
      { id: 'product', type: 'productImage', label: 'Ürün Görseli', x: 330, y: 20, width: 240, height: 300, rotation: 0, zIndex: 3, editable: true, locked: false, visible: true, style: { opacity: 1 } },
      { id: 'badge', type: 'badge', label: 'Rozet', x: 28, y: 28, width: 100, height: 26, rotation: 0, zIndex: 4, editable: true, locked: false, visible: true, content: '⚡ PRO', style: { fill: 'rgba(0,212,255,0.1)', color: '#00d4ff', fontSize: 10, fontWeight: '800', borderRadius: 6, stroke: 'rgba(0,212,255,0.25)', strokeWidth: 1, letterSpacing: 2 } },
      { id: 'headline', type: 'headline', label: 'Ana Başlık', x: 28, y: 80, width: 285, height: 90, rotation: 0, zIndex: 4, editable: true, locked: false, visible: true, content: 'Performansın\nSınırını Aş', style: { color: '#e0f7ff', fontSize: 34, fontWeight: '800', lineHeight: 1.15, fontFamily: 'Inter' } },
      { id: 'subheadline', type: 'subheadline', label: 'Özellikler', x: 28, y: 185, width: 280, height: 50, rotation: 0, zIndex: 4, editable: true, locked: false, visible: true, content: '120Hz · 5G · 48MP Kamera\nPil: 5000mAh', style: { color: '#4a9eba', fontSize: 12, lineHeight: 1.6, fontFamily: 'Inter' } },
      { id: 'price', type: 'price', label: 'Fiyat', x: 28, y: 250, width: 200, height: 36, rotation: 0, zIndex: 4, editable: true, locked: false, visible: true, content: '₺12.999 — Piyasaya Çıkış', style: { color: '#00d4ff', fontSize: 14, fontWeight: '700', fontFamily: 'Inter' } },
      { id: 'cta', type: 'ctaButton', label: 'CTA Butonu', x: 28, y: 310, width: 175, height: 44, rotation: 0, zIndex: 5, editable: true, locked: false, visible: true, content: 'Ön Sipariş Ver', style: { fill: '#0066cc', color: '#ffffff', fontSize: 13, fontWeight: '700', borderRadius: 8, fontFamily: 'Inter' } },
    ],
  },

  {
    id: 'fashion-shoes',
    name: 'Moda / Ayakkabı',
    category: 'Moda',
    previewGradient: 'linear-gradient(135deg, #1a1209 0%, #2d1f0e 50%, #4a3520 100%)',
    canvasWidth: 600,
    canvasHeight: 400,
    layers: [
      { id: 'bg', type: 'background', label: 'Arka Plan', x: 0, y: 0, width: 600, height: 400, rotation: 0, zIndex: 0, editable: true, locked: false, visible: true, style: { gradientFrom: '#1a1209', gradientTo: '#3d2b14', gradientAngle: 150 } },
      { id: 'product', type: 'productImage', label: 'Ürün Görseli', x: 300, y: 15, width: 275, height: 320, rotation: -4, zIndex: 2, editable: true, locked: false, visible: true, style: { opacity: 1 } },
      { id: 'badge', type: 'badge', label: 'Sezon Rozeti', x: 28, y: 28, width: 140, height: 28, rotation: 0, zIndex: 4, editable: true, locked: false, visible: true, content: '✦ SS25 KOLEKSİYON', style: { fill: 'rgba(217,119,6,0.15)', color: '#f59e0b', fontSize: 9, fontWeight: '700', borderRadius: 0, stroke: 'rgba(217,119,6,0.3)', strokeWidth: 1, letterSpacing: 2, uppercase: true } },
      { id: 'headline', type: 'headline', label: 'Ana Başlık', x: 28, y: 82, width: 255, height: 90, rotation: 0, zIndex: 4, editable: true, locked: false, visible: true, content: 'Tarzını\nTanımla', style: { color: '#fef3c7', fontSize: 38, fontWeight: '800', lineHeight: 1.1, fontFamily: 'Inter', letterSpacing: -1 } },
      { id: 'subheadline', type: 'subheadline', label: 'Alt Başlık', x: 28, y: 190, width: 250, height: 36, rotation: 0, zIndex: 4, editable: true, locked: false, visible: true, content: 'El yapımı İtalyan derisi', style: { color: '#92400e', fontSize: 13, fontFamily: 'Inter', letterSpacing: 0.5 } },
      { id: 'price', type: 'price', label: 'Fiyat', x: 28, y: 242, width: 200, height: 36, rotation: 0, zIndex: 4, editable: true, locked: false, visible: true, content: '₺2.850 → ₺1.990', style: { color: '#f59e0b', fontSize: 17, fontWeight: '700', fontFamily: 'Inter' } },
      { id: 'cta', type: 'ctaButton', label: 'CTA Butonu', x: 28, y: 310, width: 165, height: 44, rotation: 0, zIndex: 5, editable: true, locked: false, visible: true, content: 'Modeli İncele', style: { fill: '#d97706', color: '#0a0600', fontSize: 13, fontWeight: '800', borderRadius: 6, fontFamily: 'Inter' } },
    ],
  },

  {
    id: 'beauty',
    name: 'Kozmetik / Skincare',
    category: 'Güzellik',
    previewGradient: 'linear-gradient(135deg, #1a0a0e 0%, #2a0f18 50%, #3d1828 100%)',
    canvasWidth: 600,
    canvasHeight: 400,
    layers: [
      { id: 'bg', type: 'background', label: 'Arka Plan', x: 0, y: 0, width: 600, height: 400, rotation: 0, zIndex: 0, editable: true, locked: false, visible: true, style: { gradientFrom: '#1a0a0e', gradientTo: '#2d0f1e', gradientAngle: 145 } },
      { id: 'circle', type: 'shape', label: 'Dekor Daire', x: 380, y: 80, width: 220, height: 220, rotation: 0, zIndex: 1, editable: false, locked: true, visible: true, style: { fill: 'rgba(244,114,182,0.08)', stroke: 'rgba(244,114,182,0.2)', strokeWidth: 1 } },
      { id: 'product', type: 'productImage', label: 'Ürün Görseli', x: 345, y: 30, width: 230, height: 300, rotation: 0, zIndex: 3, editable: true, locked: false, visible: true, style: { opacity: 1 } },
      { id: 'badge', type: 'badge', label: 'Rozet', x: 28, y: 28, width: 140, height: 28, rotation: 0, zIndex: 4, editable: true, locked: false, visible: true, content: '🌸 CLEAN BEAUTY', style: { fill: 'rgba(244,114,182,0.12)', color: '#f472b6', fontSize: 10, fontWeight: '700', borderRadius: 14, stroke: 'rgba(244,114,182,0.25)', strokeWidth: 1, letterSpacing: 1 } },
      { id: 'headline', type: 'headline', label: 'Ana Başlık', x: 28, y: 82, width: 290, height: 90, rotation: 0, zIndex: 4, editable: true, locked: false, visible: true, content: 'Cilt Bakımının\nYeni Dili', style: { color: '#fce7f3', fontSize: 36, fontWeight: '700', lineHeight: 1.15, fontFamily: 'Inter' } },
      { id: 'subheadline', type: 'subheadline', label: 'Alt Başlık', x: 28, y: 188, width: 275, height: 40, rotation: 0, zIndex: 4, editable: true, locked: false, visible: true, content: 'Doğal bileşenler, görünür sonuçlar', style: { color: '#9d4477', fontSize: 13, fontFamily: 'Inter' } },
      { id: 'price', type: 'price', label: 'Fiyat', x: 28, y: 242, width: 200, height: 32, rotation: 0, zIndex: 4, editable: true, locked: false, visible: true, content: 'Seri ₺549\'dan başlıyor', style: { color: '#f9a8d4', fontSize: 14, fontWeight: '700', fontFamily: 'Inter' } },
      { id: 'cta', type: 'ctaButton', label: 'CTA Butonu', x: 28, y: 308, width: 170, height: 44, rotation: 0, zIndex: 5, editable: true, locked: false, visible: true, content: 'Rutinine Başla', style: { fill: '#be185d', color: '#fff0f7', fontSize: 13, fontWeight: '700', borderRadius: 22, fontFamily: 'Inter' } },
    ],
  },
]
